# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: weather_db_container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - weather_db_data:/var/lib/postgresql/data # Persistent data
    healthcheck: # Ensures the DB is ready before other services use it
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  weather_db_data: